# version: "3"
services:
  db:
    image: mongo:latest
    container_name: reqsminer_db
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=reqsminer
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Pwd_5h0u1D_NO7_83_tO0_w3ak_7O0o0oooO00O
    ports:
      - "2777:27017"
    restart: unless-stopped
  server:
    build:
      dockerfile: Dockerfile.server
      context: .
    container_name: reqsminer_server
    ports:
      - "2778:8080"
    depends_on:
      - db
    restart: unless-stopped
